/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fabian van Dorst (https://sketchfab.com/FabianvanDorst)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-kraken-55d900af1bfa460fb0f9304ab9fc594b
Title: The Kraken
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/kraken.glb'

const Kraken = ({ currentAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
    if(actions[currentAnimation]){
        actions[currentAnimation].play();
    }

  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="octopus_rig_07fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Submerge"
                  position={[3522.056, 4814.67, 4111.263]}
                  rotation={[Math.PI, 0.793, 2.523]}>
                  <group name="Object_5" />
                  <group
                    name="Submerge_animation"
                    position={[6144.876, 1351.74, -217.142]}
                    rotation={[2.609, -0.619, 2.348]}>
                    <group
                      name="rechts_2_groot"
                      position={[727.387, -147.869, -169.461]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_Goal"
                      position={[1118.522, -328.95, -338.46]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_klein"
                      position={[1245.525, -60.692, -224.801]}
                      rotation={[0.456, 0.766, 0.949]}
                    />
                    <group
                      name="rechts_1_groot"
                      position={[1173.394, -283.28, 470.136]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_Goal"
                      position={[1810.555, -1157.765, 1481.156]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_klein"
                      position={[1727.825, -1045.401, 1356.894]}
                      rotation={[-2.406, -0.459, -2.629]}
                    />
                    <group
                      name="rechts_midden_groot"
                      position={[426.261, -334.509, 1111.782]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_Goal"
                      position={[-2328.806, -325.29, -581.035]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_klein"
                      position={[118.419, 235.767, 459.734]}
                      rotation={[2.106, -0.097, -1.876]}
                    />
                    <group
                      name="rechts_achter_groot"
                      position={[1362.953, 1150.036, -815.627]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_Goal"
                      position={[2108.435, 26.853, -2391.916]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_klein"
                      position={[1236.033, 1052.044, -1071.738]}
                      rotation={[-0.386, -0.425, -3.127]}
                    />
                    <group
                      name="main"
                      position={[483.169, 935.673, -1955.843]}
                      rotation={[0.45, 0, Math.PI]}
                    />
                    <group
                      name="links_2_groot"
                      position={[-1390.927, 1387.613, 433.815]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_Goal"
                      position={[-2886.953, 277.467, 569.403]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_klein"
                      position={[-2810.38, 744.138, 392.916]}
                      rotation={[0.87, -1.006, -2.007]}
                    />
                    <group
                      name="links_1_groot"
                      position={[12.44, 887.032, 670.327]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1__Goal"
                      position={[-2.676, 305.367, 515.444]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1_klein"
                      position={[-351.169, 669.826, 640.03]}
                      rotation={[-0.202, -0.867, -0.225]}
                    />
                    <group
                      name="links_midden_groot"
                      position={[69.191, -711.866, 390.871]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden__Goal"
                      position={[69.191, -392.677, 1466.251]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden_klein"
                      position={[69.191, -334.678, 1404.104]}
                      rotation={[0.751, 0, 0]}
                    />
                    <group
                      name="links_achter_groot"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_Goal"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_klein"
                      position={[-1262.167, -65.253, -1130.257]}
                      rotation={[-0.791, 0.467, 3.012]}
                    />
                    <group name="alle_joints" position={[69.34, -1356.469, -134.103]}>
                      <group name="links_achter" position={[-427.358, -83.394, -311.478]}>
                        <group name="Object_34">
                          <primitive object={nodes._rootJoint} />
                        </group>
                      </group>
                      <group name="links_midden" position={[-314.762, 110.178, 488.973]}>
                        <group name="Object_46">
                          <primitive object={nodes._rootJoint_1} />
                        </group>
                      </group>
                      <group
                        name="links_1"
                        position={[-571.29, -8.018, 245.598]}
                        rotation={[0, -0.462, 0]}>
                        <group name="Object_59">
                          <primitive object={nodes._rootJoint_2} />
                        </group>
                      </group>
                      <group
                        name="links_2"
                        position={[-505.757, -21.563, 80.585]}
                        rotation={[1.473, -0.841, 1.408]}>
                        <group name="Object_72">
                          <primitive object={nodes._rootJoint_3} />
                        </group>
                      </group>
                      <group name="main_2" position={[125.194, 125.971, -84.431]}>
                        <group name="Object_86">
                          <primitive object={nodes._rootJoint_4} />
                        </group>
                      </group>
                      <group name="rechts_achter" position={[439.384, -58.123, -122.763]}>
                        <group name="Object_98">
                          <primitive object={nodes._rootJoint_5} />
                        </group>
                      </group>
                      <group name="rechts_midden" position={[74.381, -8.08, 438.205]}>
                        <group name="Object_110">
                          <primitive object={nodes._rootJoint_6} />
                        </group>
                      </group>
                      <group
                        name="rechts_1"
                        position={[324.068, 3.975, 328.857]}
                        rotation={[0, 0.698, 0]}>
                        <group name="Object_123">
                          <primitive object={nodes._rootJoint_7} />
                        </group>
                      </group>
                      <group
                        name="rechts_2"
                        position={[517.666, -60.946, 156.677]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <group name="Object_136">
                          <primitive object={nodes._rootJoint_8} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Spin"
                  position={[3522.056, 4814.67, 4111.263]}
                  rotation={[Math.PI, 0.793, 2.523]}>
                  <group name="Object_149" />
                  <group
                    name="Spin_animation"
                    position={[6144.876, 126.349, -217.142]}
                    rotation={[0, -Math.PI / 2, 0]}>
                    <group
                      name="rechts_2_groot_2"
                      position={[727.387, -147.869, -169.461]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_Goal_2"
                      position={[1118.522, -328.95, -338.46]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_klein_2"
                      position={[1245.525, -60.692, -224.801]}
                      rotation={[0.456, 0.766, 0.949]}
                    />
                    <group
                      name="rechts_1_groot_2"
                      position={[1173.394, -283.28, 470.136]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_Goal_2"
                      position={[1810.555, -1157.765, 1481.156]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_klein_2"
                      position={[1727.825, -1045.401, 1356.894]}
                      rotation={[-2.406, -0.459, -2.629]}
                    />
                    <group
                      name="rechts_midden_groot_2"
                      position={[426.261, -334.509, 1111.782]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_Goal_2"
                      position={[-2328.806, -325.29, -581.035]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_klein_2"
                      position={[118.419, 235.767, 459.734]}
                      rotation={[2.106, -0.097, -1.876]}
                    />
                    <group
                      name="rechts_achter_groot_2"
                      position={[1362.953, 1150.036, -815.627]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_Goal_2"
                      position={[2108.435, 26.853, -2391.916]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_klein_2"
                      position={[1236.033, 1052.044, -1071.738]}
                      rotation={[-0.386, -0.425, -3.127]}
                    />
                    <group
                      name="main_2_2"
                      position={[483.169, 935.673, -1955.843]}
                      rotation={[0.45, 0, Math.PI]}
                    />
                    <group
                      name="links_2_groot_2"
                      position={[-1390.927, 1387.613, 433.815]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_Goal_2"
                      position={[-2886.953, 277.467, 569.403]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_klein_2"
                      position={[-2810.38, 744.138, 392.916]}
                      rotation={[0.87, -1.006, -2.007]}
                    />
                    <group
                      name="links_1_groot_2"
                      position={[12.44, 887.032, 670.327]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1__Goal_2"
                      position={[-2.676, 305.367, 515.444]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1_klein_2"
                      position={[-351.169, 669.826, 640.03]}
                      rotation={[-0.202, -0.867, -0.225]}
                    />
                    <group
                      name="links_midden_groot_2"
                      position={[69.191, -711.866, 390.871]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden__Goal_2"
                      position={[69.191, -392.677, 1466.251]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden_klein_2"
                      position={[69.191, -334.678, 1404.104]}
                      rotation={[0.751, 0, 0]}
                    />
                    <group
                      name="links_achter_groot_2"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_Goal_2"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_klein_2"
                      position={[-1262.167, -65.253, -1130.257]}
                      rotation={[-0.791, 0.467, 3.012]}
                    />
                    <group name="alle_joints_2" position={[69.34, -1356.469, -134.103]}>
                      <group name="links_achter_2_2" position={[-427.358, -83.394, -311.478]}>
                        <group name="Object_178">
                          <primitive object={nodes._rootJoint_9} />
                        </group>
                      </group>
                      <group name="links_midden_2" position={[-314.762, 110.178, 488.973]}>
                        <group name="Object_190">
                          <primitive object={nodes._rootJoint_10} />
                        </group>
                      </group>
                      <group
                        name="links_1_2"
                        position={[-571.29, -8.018, 245.598]}
                        rotation={[0, -0.462, 0]}>
                        <group name="Object_203">
                          <primitive object={nodes._rootJoint_11} />
                        </group>
                      </group>
                      <group
                        name="links_2_2_2"
                        position={[-505.757, -21.563, 80.585]}
                        rotation={[1.473, -0.841, 1.408]}>
                        <group name="Object_216">
                          <primitive object={nodes._rootJoint_12} />
                        </group>
                      </group>
                      <group name="main_2_3" position={[125.194, 125.971, -84.431]}>
                        <group name="Object_230">
                          <primitive object={nodes._rootJoint_13} />
                        </group>
                      </group>
                      <group name="rechts_achter_2_2" position={[439.384, -58.123, -122.763]}>
                        <group name="Object_242">
                          <primitive object={nodes._rootJoint_14} />
                        </group>
                      </group>
                      <group name="rechts_midden_2_2" position={[74.381, -8.08, 438.205]}>
                        <group name="Object_254">
                          <primitive object={nodes._rootJoint_15} />
                        </group>
                      </group>
                      <group
                        name="rechts_1_2_2"
                        position={[324.068, 3.975, 328.857]}
                        rotation={[0, 0.698, 0]}>
                        <group name="Object_267">
                          <primitive object={nodes._rootJoint_16} />
                        </group>
                      </group>
                      <group
                        name="rechts_2_2_2"
                        position={[517.666, -60.946, 156.677]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <group name="Object_280">
                          <primitive object={nodes._rootJoint_17} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Movement"
                  position={[3522.056, 4814.67, 4111.263]}
                  rotation={[Math.PI, 0.793, 2.523]}>
                  <group name="Object_293" />
                  <group
                    name="Movement_animation"
                    position={[6144.876, 126.349, -217.142]}
                    rotation={[2.609, -0.619, 2.348]}>
                    <group
                      name="rechts_2_groot_3"
                      position={[727.387, -147.869, -169.461]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_Goal_3"
                      position={[1118.522, -328.95, -338.46]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_klein_3"
                      position={[1245.525, -60.692, -224.801]}
                      rotation={[0.456, 0.766, 0.949]}
                    />
                    <group
                      name="rechts_1_groot_3"
                      position={[1173.394, -283.28, 470.136]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_Goal_3"
                      position={[1810.555, -1157.765, 1481.156]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_klein_3"
                      position={[1727.825, -1045.401, 1356.894]}
                      rotation={[-2.406, -0.459, -2.629]}
                    />
                    <group
                      name="rechts_midden_groot_3"
                      position={[426.261, -334.509, 1111.782]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_Goal_3"
                      position={[-2328.806, -325.29, -581.035]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_klein_3"
                      position={[118.419, 235.767, 459.734]}
                      rotation={[2.106, -0.097, -1.876]}
                    />
                    <group
                      name="rechts_achter_groot_3"
                      position={[1362.953, 1150.036, -815.627]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_Goal_3"
                      position={[2108.435, 26.853, -2391.916]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_klein_3"
                      position={[1236.033, 1052.044, -1071.738]}
                      rotation={[-0.386, -0.425, -3.127]}
                    />
                    <group
                      name="main_3"
                      position={[483.169, 935.673, -1955.843]}
                      rotation={[0.45, 0, Math.PI]}
                    />
                    <group
                      name="links_2_groot_3"
                      position={[-1390.927, 1387.613, 433.815]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_Goal_3"
                      position={[-2886.953, 277.467, 569.403]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_klein_3"
                      position={[-2810.38, 744.138, 392.916]}
                      rotation={[0.87, -1.006, -2.007]}
                    />
                    <group
                      name="links_1_groot_3"
                      position={[12.44, 887.032, 670.327]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1__Goal_3"
                      position={[-2.676, 305.367, 515.444]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1_klein_3"
                      position={[-351.169, 669.826, 640.03]}
                      rotation={[-0.202, -0.867, -0.225]}
                    />
                    <group
                      name="links_midden_groot_3"
                      position={[69.191, -711.866, 390.871]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden__Goal_3"
                      position={[69.191, -392.677, 1466.251]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden_klein_3"
                      position={[69.191, -334.678, 1404.104]}
                      rotation={[0.751, 0, 0]}
                    />
                    <group
                      name="links_achter_groot_3"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_Goal_3"
                      position={[-1522.889, -563.559, -1342.6]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_klein_3"
                      position={[-1262.167, -65.253, -1130.257]}
                      rotation={[-0.791, 0.467, 3.012]}
                    />
                    <group name="alle_joints_3" position={[69.34, -1356.469, -134.103]}>
                      <group name="links_achter_3" position={[-427.358, -83.394, -311.478]}>
                        <group name="Object_322">
                          <primitive object={nodes._rootJoint_18} />
                        </group>
                      </group>
                      <group name="links_midden_3" position={[-314.762, 110.178, 488.973]}>
                        <group name="Object_334">
                          <primitive object={nodes._rootJoint_19} />
                        </group>
                      </group>
                      <group
                        name="links_1_3"
                        position={[-571.29, -8.018, 245.598]}
                        rotation={[0, -0.462, 0]}>
                        <group name="Object_347">
                          <primitive object={nodes._rootJoint_20} />
                        </group>
                      </group>
                      <group
                        name="links_2_3"
                        position={[-505.757, -21.563, 80.585]}
                        rotation={[1.473, -0.841, 1.408]}>
                        <group name="Object_360">
                          <primitive object={nodes._rootJoint_21} />
                        </group>
                      </group>
                      <group name="main_2_4" position={[125.194, 125.971, -84.431]}>
                        <group name="Object_374">
                          <primitive object={nodes._rootJoint_22} />
                        </group>
                      </group>
                      <group name="rechts_achter_3" position={[439.384, -58.123, -122.763]}>
                        <group name="Object_386">
                          <primitive object={nodes._rootJoint_23} />
                        </group>
                      </group>
                      <group name="rechts_midden_3" position={[74.381, -8.08, 438.205]}>
                        <group name="Object_398">
                          <primitive object={nodes._rootJoint_24} />
                        </group>
                      </group>
                      <group
                        name="rechts_1_3"
                        position={[324.068, 3.975, 328.857]}
                        rotation={[0, 0.698, 0]}>
                        <group name="Object_411">
                          <primitive object={nodes._rootJoint_25} />
                        </group>
                      </group>
                      <group
                        name="rechts_2_3"
                        position={[517.666, -60.946, 156.677]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <group name="Object_424">
                          <primitive object={nodes._rootJoint_26} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Splash"
                  position={[3522.056, 4814.67, 4111.263]}
                  rotation={[Math.PI, 0.793, 2.523]}>
                  <group name="Object_437" />
                  <group
                    name="Splash_animation"
                    position={[6324.971, 235.802, -417.699]}
                    rotation={[2.609, -0.619, 2.348]}>
                    <group
                      name="rechts_2_groot_4"
                      position={[729.127, -132.501, -160.342]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_Goal_4"
                      position={[1120.262, -313.582, -329.341]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_klein_4"
                      position={[1247.265, -45.324, -215.682]}
                      rotation={[0.456, 0.766, 0.949]}
                    />
                    <group
                      name="rechts_1_groot_4"
                      position={[1175.134, -267.912, 479.255]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_Goal_4"
                      position={[1812.296, -1142.397, 1490.275]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_klein_4"
                      position={[1729.566, -1030.032, 1366.013]}
                      rotation={[-2.406, -0.459, -2.629]}
                    />
                    <group
                      name="rechts_midden_groot_4"
                      position={[428.001, -319.141, 1120.901]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_Goal_4"
                      position={[-2327.066, -309.921, -571.916]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_klein_4"
                      position={[74.913, -148.441, 231.752]}
                      rotation={[2.106, -0.097, -1.876]}
                    />
                    <group
                      name="rechts_achter_groot_4"
                      position={[1364.693, 1165.404, -806.508]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_Goal_4"
                      position={[2110.175, 42.221, -2382.797]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_klein_4"
                      position={[1237.773, 1067.412, -1062.619]}
                      rotation={[-0.386, -0.425, -3.127]}
                    />
                    <group
                      name="main_4"
                      position={[484.909, 951.041, -1946.724]}
                      rotation={[0.45, 0, Math.PI]}
                    />
                    <group
                      name="links_2_groot_4"
                      position={[-1389.187, 1402.981, 442.934]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_Goal_4"
                      position={[-2885.212, 292.835, 578.522]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_klein_4"
                      position={[-2808.64, 759.507, 402.036]}
                      rotation={[0.87, -1.006, -2.007]}
                    />
                    <group
                      name="links_1_groot_4"
                      position={[14.18, 902.4, 679.446]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1__Goal_4"
                      position={[-0.936, 320.735, 524.563]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1_klein_4"
                      position={[-349.429, 685.195, 649.149]}
                      rotation={[-0.202, -0.867, -0.225]}
                    />
                    <group
                      name="links_midden_groot_4"
                      position={[70.931, -696.498, 399.99]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden__Goal_4"
                      position={[70.931, -377.309, 1475.37]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden_klein_4"
                      position={[70.931, -319.31, 1413.223]}
                      rotation={[0.751, 0, 0]}
                    />
                    <group
                      name="links_achter_groot_4"
                      position={[-1521.149, -548.19, -1333.481]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_Goal_4"
                      position={[-1521.149, -548.19, -1333.481]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_klein_4"
                      position={[-1260.427, -49.885, -1121.138]}
                      rotation={[-0.791, 0.467, 3.012]}
                    />
                    <group name="alle_joints_4" position={[322.107, -1341.1, 10.597]}>
                      <group name="links_achter_4" position={[-389.75, -83.394, -447.058]}>
                        <group name="Object_466">
                          <primitive object={nodes._rootJoint_27} />
                        </group>
                      </group>
                      <group name="links_midden_4" position={[-277.154, 110.178, 353.393]}>
                        <group name="Object_478">
                          <primitive object={nodes._rootJoint_28} />
                        </group>
                      </group>
                      <group
                        name="links_1_4"
                        position={[-533.682, -8.018, 110.018]}
                        rotation={[0, -0.462, 0]}>
                        <group name="Object_491">
                          <primitive object={nodes._rootJoint_29} />
                        </group>
                      </group>
                      <group
                        name="links_2_4"
                        position={[-468.149, -21.563, -54.995]}
                        rotation={[1.473, -0.841, 1.408]}>
                        <group name="Object_504">
                          <primitive object={nodes._rootJoint_30} />
                        </group>
                      </group>
                      <group name="main_2_5" position={[162.802, 125.971, -220.011]}>
                        <group name="Object_518">
                          <primitive object={nodes._rootJoint_31} />
                        </group>
                      </group>
                      <group name="rechts_achter_4" position={[476.992, -58.123, -258.343]}>
                        <group name="Object_530">
                          <primitive object={nodes._rootJoint_32} />
                        </group>
                      </group>
                      <group name="rechts_midden_4" position={[111.99, -8.08, 302.625]}>
                        <group name="Object_542">
                          <primitive object={nodes._rootJoint_33} />
                        </group>
                      </group>
                      <group
                        name="rechts_1_4"
                        position={[361.676, 3.975, 193.276]}
                        rotation={[0, 0.698, 0]}>
                        <group name="Object_555">
                          <primitive object={nodes._rootJoint_34} />
                        </group>
                      </group>
                      <group
                        name="rechts_2_4"
                        position={[555.274, -60.946, 21.096]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <group name="Object_568">
                          <primitive object={nodes._rootJoint_35} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Idle"
                  position={[3522.056, 4814.67, 4111.263]}
                  rotation={[Math.PI, 0.793, 2.523]}>
                  <group name="Object_581" />
                  <group
                    name="Idle_animation"
                    position={[6324.971, 235.802, -417.699]}
                    rotation={[2.609, -0.619, 2.348]}>
                    <group
                      name="rechts_2_groot_5"
                      position={[729.127, -132.501, -160.342]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_Goal_5"
                      position={[1120.262, -313.582, -329.341]}
                      rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                    />
                    <group
                      name="rechts_2_klein_5"
                      position={[1247.265, -45.324, -215.682]}
                      rotation={[0.456, 0.766, 0.949]}
                    />
                    <group
                      name="rechts_1_groot_5"
                      position={[1175.134, -267.912, 479.255]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_Goal_5"
                      position={[1812.296, -1142.397, 1490.275]}
                      rotation={[-2.467, -0.58, -2.728]}
                    />
                    <group
                      name="rechts_1_klein_5"
                      position={[1729.566, -1030.032, 1366.013]}
                      rotation={[-2.406, -0.459, -2.629]}
                    />
                    <group
                      name="rechts_midden_groot_5"
                      position={[428.001, -319.141, 1120.901]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_Goal_5"
                      position={[-2327.066, -309.921, -571.916]}
                      rotation={[1.834, 0, Math.PI]}
                    />
                    <group
                      name="rechts_midden_klein_5"
                      position={[74.913, -148.441, 231.752]}
                      rotation={[2.106, -0.097, -1.876]}
                    />
                    <group
                      name="rechts_achter_groot_5"
                      position={[1364.693, 1165.404, -806.508]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_Goal_5"
                      position={[2110.175, 42.221, -2382.797]}
                      rotation={[-0.422, 0, Math.PI]}
                    />
                    <group
                      name="rechts_achter_klein_5"
                      position={[1237.773, 1067.412, -1062.619]}
                      rotation={[-0.386, -0.425, -3.127]}
                    />
                    <group
                      name="main_5"
                      position={[484.909, 951.041, -1946.724]}
                      rotation={[0.45, 0, Math.PI]}
                    />
                    <group
                      name="links_2_groot_5"
                      position={[-1389.187, 1402.981, 442.934]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_Goal_5"
                      position={[-2885.212, 292.835, 578.522]}
                      rotation={[1.554, -0.358, -1.686]}
                    />
                    <group
                      name="links_2_klein_5"
                      position={[-2808.64, 759.507, 402.036]}
                      rotation={[0.87, -1.006, -2.007]}
                    />
                    <group
                      name="links_1_groot_5"
                      position={[14.18, 902.4, 679.446]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1__Goal_5"
                      position={[-0.936, 320.735, 524.563]}
                      rotation={[1.579, -0.254, -2.42]}
                    />
                    <group
                      name="links_1_klein_5"
                      position={[-349.429, 685.195, 649.149]}
                      rotation={[-0.202, -0.867, -0.225]}
                    />
                    <group
                      name="links_midden_groot_5"
                      position={[70.931, -696.498, 399.99]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden__Goal_5"
                      position={[70.931, -377.309, 1475.37]}
                      rotation={[-1.983, 0, -Math.PI]}
                    />
                    <group
                      name="links_midden_klein_5"
                      position={[70.931, -319.31, 1413.223]}
                      rotation={[0.751, 0, 0]}
                    />
                    <group
                      name="links_achter_groot_5"
                      position={[-1521.149, -548.19, -1333.481]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_Goal_5"
                      position={[-1521.149, -548.19, -1333.481]}
                      rotation={[-1.072, 0, Math.PI]}
                    />
                    <group
                      name="links_achter_klein_5"
                      position={[-1260.427, -49.885, -1121.138]}
                      rotation={[-0.791, 0.467, 3.012]}
                    />
                    <group name="alle_joints_5" position={[322.107, -1341.1, 10.597]}>
                      <group name="links_achter_5" position={[-389.75, -83.394, -447.058]}>
                        <group name="Object_610">
                          <primitive object={nodes._rootJoint_36} />
                        </group>
                      </group>
                      <group name="links_midden_5" position={[-277.154, 110.178, 353.393]}>
                        <group name="Object_622">
                          <primitive object={nodes._rootJoint_37} />
                        </group>
                      </group>
                      <group
                        name="links_1_5"
                        position={[-533.682, -8.018, 110.018]}
                        rotation={[0, -0.462, 0]}>
                        <group name="Object_635">
                          <primitive object={nodes._rootJoint_38} />
                        </group>
                      </group>
                      <group
                        name="links_2_5"
                        position={[-468.149, -21.563, -54.995]}
                        rotation={[1.473, -0.841, 1.408]}>
                        <group name="Object_648">
                          <primitive object={nodes._rootJoint_39} />
                        </group>
                      </group>
                      <group name="main_2_6" position={[162.802, 125.971, -220.011]}>
                        <group name="Object_662">
                          <primitive object={nodes._rootJoint_40} />
                        </group>
                      </group>
                      <group name="rechts_achter_5" position={[476.992, -58.123, -258.343]}>
                        <group name="Object_674">
                          <primitive object={nodes._rootJoint_41} />
                        </group>
                      </group>
                      <group name="rechts_midden_5" position={[111.99, -8.08, 302.625]}>
                        <group name="Object_686">
                          <primitive object={nodes._rootJoint_42} />
                        </group>
                      </group>
                      <group
                        name="rechts_1_5"
                        position={[361.676, 3.975, 193.276]}
                        rotation={[0, 0.698, 0]}>
                        <group name="Object_699">
                          <primitive object={nodes._rootJoint_43} />
                        </group>
                      </group>
                      <group
                        name="rechts_2_5"
                        position={[555.274, -60.946, 21.096]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <group name="Object_712">
                          <primitive object={nodes._rootJoint_44} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Rig" position={[-484.909, 1336.372, 635.488]}>
                  <group
                    name="rechts_2_groot_6"
                    position={[729.127, -132.501, -160.342]}
                    rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                  />
                  <group
                    name="rechts_2_Goal_6"
                    position={[1120.262, -313.582, -329.341]}
                    rotation={[-Math.PI / 2, 0.434, Math.PI / 2]}
                  />
                  <group
                    name="rechts_2_klein_6"
                    position={[1247.265, -45.324, -215.682]}
                    rotation={[0.456, 0.766, 0.949]}
                  />
                  <group
                    name="rechts_1_groot_6"
                    position={[1175.134, -267.912, 479.255]}
                    rotation={[-2.467, -0.58, -2.728]}
                  />
                  <group
                    name="rechts_1_Goal_6"
                    position={[1812.296, -1142.397, 1490.275]}
                    rotation={[-2.467, -0.58, -2.728]}
                  />
                  <group
                    name="rechts_1_klein_6"
                    position={[1729.566, -1030.032, 1366.013]}
                    rotation={[-2.406, -0.459, -2.629]}
                  />
                  <group
                    name="rechts_midden_groot_6"
                    position={[428.001, -319.141, 1120.901]}
                    rotation={[1.834, 0, Math.PI]}
                  />
                  <group
                    name="rechts_midden_Goal_6"
                    position={[-2327.066, -309.921, -571.916]}
                    rotation={[1.834, 0, Math.PI]}
                  />
                  <group
                    name="rechts_midden_klein_6"
                    position={[74.913, -148.441, 231.752]}
                    rotation={[2.106, -0.097, -1.876]}
                  />
                  <group
                    name="rechts_achter_groot_6"
                    position={[1364.693, 1165.404, -806.508]}
                    rotation={[-0.422, 0, Math.PI]}
                  />
                  <group
                    name="rechts_achter_Goal_6"
                    position={[2110.175, 42.221, -2382.797]}
                    rotation={[-0.422, 0, Math.PI]}
                  />
                  <group
                    name="rechts_achter_klein_6"
                    position={[1237.773, 1067.412, -1062.619]}
                    rotation={[-0.386, -0.425, -3.127]}
                  />
                  <group
                    name="main_6"
                    position={[484.909, 951.041, -1946.724]}
                    rotation={[0.45, 0, Math.PI]}
                  />
                  <group
                    name="links_2_groot_6"
                    position={[-1389.187, 1402.981, 442.934]}
                    rotation={[1.554, -0.358, -1.686]}
                  />
                  <group
                    name="links_2_Goal_6"
                    position={[-2885.212, 292.835, 578.522]}
                    rotation={[1.554, -0.358, -1.686]}
                  />
                  <group
                    name="links_2_klein_6"
                    position={[-2808.64, 759.507, 402.036]}
                    rotation={[0.87, -1.006, -2.007]}
                  />
                  <group
                    name="links_1_groot_6"
                    position={[14.18, 902.4, 679.446]}
                    rotation={[1.579, -0.254, -2.42]}
                  />
                  <group
                    name="links_1__Goal_6"
                    position={[-0.936, 320.735, 524.563]}
                    rotation={[1.579, -0.254, -2.42]}
                  />
                  <group
                    name="links_1_klein_6"
                    position={[-349.429, 685.195, 649.149]}
                    rotation={[-0.202, -0.867, -0.225]}
                  />
                  <group
                    name="links_midden_groot_6"
                    position={[70.931, -696.498, 399.99]}
                    rotation={[-1.983, 0, -Math.PI]}
                  />
                  <group
                    name="links_midden__Goal_6"
                    position={[70.931, -377.309, 1475.37]}
                    rotation={[-1.983, 0, -Math.PI]}
                  />
                  <group
                    name="links_midden_klein_6"
                    position={[70.931, -319.31, 1413.223]}
                    rotation={[0.751, 0, 0]}
                  />
                  <group
                    name="links_achter_groot_6"
                    position={[-1521.149, -548.19, -1333.481]}
                    rotation={[-1.072, 0, Math.PI]}
                  />
                  <group
                    name="links_achter_Goal_6"
                    position={[-1521.149, -548.19, -1333.481]}
                    rotation={[-1.072, 0, Math.PI]}
                  />
                  <group
                    name="links_achter_klein_6"
                    position={[-1260.427, -49.885, -1121.138]}
                    rotation={[-0.791, 0.467, 3.012]}
                  />
                  <group name="alle_joints_6" position={[322.107, -1341.1, 10.597]}>
                    <group name="Object_751">
                      <primitive object={nodes._rootJoint_45} />
                      <skinnedMesh
                        name="Object_851"
                        geometry={nodes.Object_851.geometry}
                        material={materials['default']}
                        skeleton={nodes.Object_851.skeleton}
                      />
                      <group name="Object_850" />
                    </group>
                  </group>
                </group>
                <group name="Kraken" />
                <group name="Water" position={[-190, 194.383, 440]}>
                  <mesh
                    name="Water_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Water_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Kraken
